### PR TITLE
[Counterfactual] Display option to refresh balances

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #

## How this PR fixes it

- Adds a section to the assets page for counterfactual safes to refresh balance and a link to block explorer
- The refresh button has a cooldown of 15s to mitigate potential spam

## How to test it

1. Create a counterfactual safe
2. Open the assets page
3. Observe a new section
4. Disconnect your wallet
5. Send ETH to your counterfactual safe
6. Wait until the transaction has been executed
7. Press "Refresh balance"
8. The new balance should be visible within the next 15s

## Screenshots
Screenshot 2024-02-08 at 21 20 47

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Review by schmanu — APPROVED** [review]
LGTM!

**Comment by francovenica** [comment]
So the section is there, and the button has the 15 sec limit, but is hard to test since the assets, in my case update really fast, so you don't know if the button is doing its job or not.
I don't see calls in the network that I can block or something to make the button fail on purpose.

Is hard for me to say that the button works fine. I don't see any issues, but I'll ask Usame to look it together before merging it.

**Comment by usame-algan** [comment]
> Is hard for me to say that the button works fine. I don't see any issues, but I'll ask Usame to look it together before merging it.

I updated the PR description with steps on how to test this. This is easiest to test when there is no wallet connected. Let me know if it works for you.

**Comment by francovenica** [comment]
Even disconnected is pretty fast, but I was able to see it. 

Found an issue I didn't see before:
1 - Changing pages (like going to tx and back) re enables the button, allowing spamming it.

**Comment by usame-algan** [comment]
> Changing pages (like going to tx and back) re enables the button, allowing spamming it.

I think this is fine for now as reloading the page also enables the button again. We will add tracking to this button and in case it gets spammed we can take more measures.

**Comment by liliya-soroka** [comment]
Is it expected? ( Just created counterfactual safe )
image

**Comment by liliya-soroka** [comment]
Ok, verified

**Pull request merged**
