### PR TITLE
feat: Edit proposer dialog [SW-391] [SW-396]

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves [SW-391](https://www.notion.so/safe-global/Edit-existing-proposer-12a8180fe573805397cfc85e292bc235)

## How this PR fixes it

- Creates a new Dialog called `EditProposerDialog`
- Refactors `DeleteProposerDialog` to follow the same pattern
- Refactors `AddProposer` to `UpsertProposer` to handle editing

## How to test it

1. Create a proposer
2. Go to the settings page and observe a new edit icon next to them
3. Press the button
4. Observe a new dialog to edit the proposer label

## Screenshots

Screenshot 2024-10-28 at 11 18 53

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by usame-algan** [comment]
@jmealy I found a way to refactor the components to solve this issue you mentioned in the other PR: https://github.com/safe-global/safe-wallet-web/pull/4390#discussion_r1814407634

**Review by jmealy — COMMENTED** [review]
The add proposer dialog is not working for me now. The continue button remains disabled even after filling out the form

Also could we disable the continue button in the edit dialog until a change has been made? Right now you can sign the message and send the request without having made any changes

**Comment by usame-algan** [comment]
> The add proposer dialog is not working for me now. The continue button remains disabled even after filling out the form
> 
> Also could we disable the continue button in the edit dialog until a change has been made? Right now you can sign the message and send the request without having made any changes

Good catch! I adjusted the condition so the button should be enabled now when adding a new proposer. Am also checking the formState to keep the button disabled if its not valid.

**Review by jmealy — APPROVED** [review]
Ok, looks good!

**Pull request merged**
