### PR TITLE
Release/1.15.0

### PR DESCRIPTION
**Pull request by usame-algan**
## Features

- #2067
- #2307 

## Fixes

- #2228
- #2238
- #2232
- #2255
- #2267
- #2273

### CODE REVIEW

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
There are some issues that Liliya reported in the document for tx flow

Other issues:
Trying to create a safe with Trezor, ledger or mobile pairing in GNO network shows me this error.
image

In the safe creation, the QR code icon to add an owner address only works once:
Open it once, cancel the upload, click the icon again and nothing happens. You have to hard reload the page in order for it to work again
This issue does not happen in prod.

**Comment by schmanu** [comment]
@francovenica:

I cannot reproduce the Safe creation errors.
I am using ledger and tried it on Polygon, Goerli and Gnosis Chain.
On all chains it just worked. But I found a user who reported a similar issue yesterday. 

When searching for this error I found this re-opened issue for our safe-core-sdk:
https://github.com/safe-global/safe-core-sdk/issues/128

It seems that on some networks this occasionally happens. The RPC provider is not returning the deployed Safe contracts correctly.

Could you retry this on your end? If it is resolved it is not on our end but likely related to RPC problems.

**Comment by usame-algan** [comment]
> In the safe creation, the QR code icon to add an owner address only works once:
Open it once, cancel the upload, click the icon again and nothing happens. You have to hard reload the page in order for it to work again
This issue does not happen in prod.

I am not able to reproduce this. Can you try again and send a video of the issue?

**Comment by francovenica** [comment]
@schmanu I don't have funds for other networks, but I kept trying in GNO and I keep having the same issue

**Comment by francovenica** [comment]
The RC is fine.

Check the latest fixes:
The tenderly simulation
The fix on the designs

It was decided that other issues still in the board are low prio and can wait until the next release.

**Comment by liliya-soroka** [comment]
@francovenica 
This morning the next issues were fixed before going live:
1. https://github.com/safe-global/safe-wallet-web/pull/2280/commits/00c044f793498b25b60aaf5b07368a5d9d6ce991
2. https://github.com/safe-global/safe-wallet-web/pull/2280/commits/ff5f450e38af6113c2c3d577ab15a6de84f183ce

**Pull request merged**
