### PR TITLE
[EPIC] SEP #5 - Update header/widget

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves missing `type`/staging URL for SEP #5 claiming data

## How this PR fixes it

The forthcoming claiming data for SEP #5 will be tagged under `user_v2`. This adds the new `type`, as well as the staging URL.

## How to test it

Open the PR deployment on a Safe that is part of the [test allocation](https://docs.google.com/spreadsheets/d/1_T-PfjItlejyYfWlUfvQGXCtF_wCPb_508xi1NC7edQ/edit#gid=216932284) and observe the increased allocation in the header/governance app widget.

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Review by schmanu — APPROVED** [review]

**Comment by liliya-soroka** [comment]
incorrect amount in displayed 
image - https://sep5_type--walletweb.review-wallet-web.5afe.dev/home?safe=gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c

Same in my safe on prod without SEP5 allocation 
image - https://app.safe.global/home?safe=gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c

Please, check that the test data is correct

**Comment by iamacook** [comment]
> incorrect amount in displayed image - https://sep5_type--walletweb.review-wallet-web.5afe.dev/home?safe=gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c
> 
> Same in my safe on prod without SEP5 allocation image - https://app.safe.global/home?safe=gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c
> 
> Please, check that the test data is correct

I will need to deploy a new test contract as the test redemption deadline has now passed.

**Comment by iamacook** [comment]
> incorrect amount in displayed image - https://sep5_type--walletweb.review-wallet-web.5afe.dev/home?safe=gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c
> 
> Same in my safe on prod without SEP5 allocation image - https://app.safe.global/home?safe=gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c
> 
> Please, check that the test data is correct

There was an issue with the test data which has now been fixed. I can see the difference with the following Safe: `gor:0xAecDFD3A19f777F0c03e6bf99AAfB59937d6467b`.

**Comment by liliya-soroka** [comment]
Verified

**Pull request merged**
