### PR TITLE
Feat: Sygnum safe app recovery method [SW-168]

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves https://www.notion.so/safe-global/Tweak-Recovery-Hub-UI-with-Sygnum-being-live-1b5bde2ee7a841568f05962d9d02c634

Screenshot 2024-09-12 at 16 23 28

## How this PR fixes it

Sygnum Safe App will be released soon, so it becomes an active recovery option and not a waitlist.

## How to test it

* Go to Settings -> Security -> Recovery Setup
* Choose Sygnum
* Press Open App
* Check analytics events

## Checklist
* [x ] I've documented how it affects the analytics (if at all) 📊

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]
Code Looks good!

**Comment by liliya-soroka** [comment]
the ticket is moved back with questions https://www.notion.so/safe-global/Tweak-Recovery-Hub-UI-with-Sygnum-being-live-1b5bde2ee7a841568f05962d9d02c634?pvs=4

**Comment by katspaugh** [comment]
@liliya-soroka fixed ✅

**Comment by liliya-soroka** [comment]
image
cc @TanyaEfremova

**Comment by TanyaEfremova** [comment]
Can we adjust the style of the card according to design, please? [See Figma](https://www.figma.com/design/pO43pjVwR34Uy1ihMsY3OM/Recovery-Hub?node-id=2237-32005&t=UKOnAKsRSGU02VrX-1)

**Comment by katspaugh** [comment]
Updated the styles.

Screenshot 2024-09-19 at 12 38 00

**Pull request merged**
