### PR TITLE
Feat: show balances in the Safe List

### LINKED ISSUE #3610: [Login page] Show balances and pending actions
## What is the feature about

A follow-up on the redesigned Login Page.
Use the new CGW endpoint to fetch balances and pending actions.

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #3610 

Screenshot 2024-04-10 at 18 26 53

## How this PR fixes it

I've added @iamacook's new endpoint for balances and pending transaction counts (the counts aren't displayed yet), as well as an infinite scroll pagination for the safe list.

Gateway SDK PR: https://github.com/safe-global/safe-gateway-typescript-sdk/pull/161

## Fiat formatting

I've also adjusted the currency formatting function a bit: it will now _not_ show cents for amounts greater than 1k.

### CODE REVIEW

**Review by jmealy — CHANGES_REQUESTED** [review]
The balances on mobile are not positioned:
image

**Comment by katspaugh** [comment]
@jmealy fixed, thank you!

Screenshot 2024-04-26 at 09 20 19Screenshot 2024-04-26 at 09 20 28

**Review by jmealy — APPROVED** [review]
Looks good ✨

**Comment by katspaugh** [comment]
Added pending actions also:

Screenshot 2024-04-26 at 14 16 33

**Comment by francovenica** [comment]
The "To confirm" tag shows whenever there is a tx that you (as connected owner) have not signed, even for safes 1/x, so technically there is nothing to confirm there. I'd say that, for safes 1/x the tag should not show.
image


Question:
Currently in prod, if you are not connected with an owner, no safes are shown (except in the watch list). Now it seems the safes I saw with a connected owner are being stored so even if I'm not connected the full list loads.
Is this an intended change? maybe for the new pagination?
image
image

**Comment by katspaugh** [comment]
Fixed the cached list on disconnect, figuring out the "1 to confirm" thing with Aaron.

**Comment by katspaugh** [comment]
@francovenica Aaron has fixed it on the CGW side. 👍

**Comment by iamacook** [comment]
> The user still see the "1 to confirm" even tho the current connected user cannot confirm it

I am looking into this issue from the backend perspective now.

**Comment by katspaugh** [comment]
@francovenica I've added ENS lookup for the Safe List here.

**Comment by iamacook** [comment]
@francovenica, the "1 to confirm" issue appears to be solved now that we've merged the fix on our end.

**Comment by francovenica** [comment]
@iamacook Yes. It works fine now.

LGTM

**Pull request merged**
