### PR TITLE
fix: cannot connect with WC to Opensea

### PR DESCRIPTION
**Pull request by compojoom**
If the user is trying to connect with WC to Opensea and the user is on a chain other than mainnet the first connection attempt fails. The second one succeeds. This is because when opensea sees the list of optional chains, after establishing a session it sends a request, but the request is for the optional chain and not for the required one and we end up blocking it. By giving up on the optional namespace Opensea sends the request to the requried chain.

## How to test it
Go to opensea to a collection that is on let's say OP. Try to establish WC connection to your safe that is also on OP. Establishing a connection should work.

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by compojoom** [comment]
@katspaugh - I've been thinking about the failing tests. 
It's obviously expected that those 2 will fail as now I don't pass the optional namespace. This actually made me wonder whether the app will continue to work as expected. While reading the WC docs I realized that one can update the session with additional chains and accounts. So I thought - ok, so if we switch from let's say OP to ETH, we could pass the new account to WC and it would pass it down to the dapap. To my surprise we already do that :D So the dapp recognises that we are switching the account in the wallet and updates respectively. Now with my fix this no longer works, because we have an isUnsupportedChain check:
https://github.com/safe-global/safe-wallet-web/blob/e25b770d406ff9fe5c48adfcec1a346d234df7c2/src/features/walletconnect/services/WalletConnectWallet.ts#L150

I've find another way to make this work. First we approve with requiredChain, then immediately after that we update the session with the Optional namespace. Then later our changes to the accounts will be properly propagated to all supported chains. 

The test still fails though, but that is I guess expected as we are not really testing whether approve has succeeded, but rather whether it was called with the "correct" arguments :(

**Comment by compojoom** [comment]
ok, now it should be fine everywhere :(

**Review by usame-algan — APPROVED** [review]
Code looks good and we tested the happy path together (Connecting to OpenSea). I suggest we do regression tests for other WC cases before merging. Things like switching to a different Safe on the same network, switching to a different Safe on a different network etc.

**Review by katspaugh — APPROVED** [review]
👍

**Comment by francovenica** [comment]
LGTM

Connecting with a different network than the one expected by OpenSea, it changes the network in openSea itself and connects fine.

**Pull request merged**
