### PR TITLE
fix: check deployments of migration contracts, upgrade safe-deployments

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves
If only worldchain is selected as network during Safe creation the SetupToL2 call was missing during deployment.

## How this PR fixes it
- Upgrade `safe-deployments` to latest version
- Check for all network options that they have a SetupToL2 deployment available if multiple networks are selected
- Check that target network has MigrateToL2 deployment when adding networks to existing Safes

## How to test it
- Create a Safe on only Worldchain
- Observe that it has the correct masterCopy
- Add Worldchain to a legacy L1 Safe
- Observe that it can be migrated

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [x] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by liliya-soroka** [comment]
1.4.1L2 for single safe creation
image

**Review by usame-algan — APPROVED** [review]

**Comment by liliya-soroka** [comment]
Verified

**Comment by liliya-soroka** [comment]
@schmanu , is it ok, if 1.3.0L2 (non canonical) is suggested to migrate to 1.4.1L2?
Optimism 1.3.0+L2 ( non-canonical) to 1.4.1+L2 on Worldchain ?
image

**Review by usame-algan — APPROVED** [review]

**Comment by schmanu** [comment]
> @schmanu , is it ok, if 1.3.0L2 (non canonical) is suggested to migrate to 1.4.1L2? Optimism 1.3.0+L2 ( non-canonical) to 1.4.1+L2 on Worldchain ? image

Downgrading our safe-deployments should fix this as we won't offer replaying such Safes anymore.
They are missing on our /singleton endpoint on the tx service.

**Comment by liliya-soroka** [comment]
Blocked again 
image

**Pull request merged**
