### PR TITLE
Release 1.21.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* Feat: pinned apps on top of all apps + rm list view switch (#2699)

## Bug fixes
* Fix: adjust WalletConnect events (#2717)
* Fix: soften fallback handler warning (#2716)
* Fix: render mobile pairing correctly (#2718)

## Tests
* Tests: Update skipped tests (#2723)
* Tests: Fix Cypress tests (#2706)

### CODE REVIEW

**Comment by francovenica** [comment]
The logo in the onboard looks like this:
image

**Comment by francovenica** [comment]
I connected with Opensea and the tab in the browser got in a state were the icon flickers constantly. The connection was done, no other messages should be pending of signing, so there should be no reason for the icon to flicker like that

RC1

**Comment by francovenica** [comment]
There is an issue when, if you try to upload a file (like import in the address book) the pages refreshes and the URL has a new parameter that idk where it comes from. This doesn't happen in prod

Navigate to the Address book
Click on import
Click on the "choose a file" link to open the file explorer.

RC2

**Comment by francovenica** [comment]
The rest of the RC is fine. I did a smoke navigating the page, creating safes, signgin and executing tx with different browsers... Looks good

**Comment by liliya-soroka** [comment]
> There is an issue when, if you try to upload a file (like import in the address book) the pages refreshes and the URL has a new parameter that idk where it comes from. This doesn't happen in prod
> 
> Navigate to the Address book Click on import Click on the "choose a file" link to open the file explorer.
> 
> RC2 [ RC2 ](https://user-images.githubusercontent.com/4503659/279870532-636b4a4c-2d9b-4f2b-8e47-f4a301391b9a.gif) [ ](https://user-images.githubusercontent.com/4503659/279870532-636b4a4c-2d9b-4f2b-8e47-f4a301391b9a.gif)

Let's report it as a separate UI issue and fix later. Looks like Windows specific problem.

**Comment by liliya-soroka** [comment]
> I connected with Opensea and the tab in the browser got in a state were the icon flickers constantly. The connection was done, no other messages should be pending of signing, so there should be no reason for the icon to flicker like that.
> 
> I tried in prod and didn't happened there.
> 
> Beyond that flickr, no further issues seem to be regarding connecting to a Dapp RC1 [ RC1 ](https://user-images.githubusercontent.com/4503659/279841165-43fd3aa7-a731-4e75-a3cd-2c11bea9f3dd.gif) [ ](https://user-images.githubusercontent.com/4503659/279841165-43fd3aa7-a731-4e75-a3cd-2c11bea9f3dd.gif)
> 
> EDIT: I got the same issue duing a swap in the "Swap" Dapp as well

we were not able to reproduce it and find the problem in the code. Let's try to find the steps and report it as a new issue out of the RC

**Comment by katspaugh** [comment]
I've removed the #-href from the upload link in the Address book, so hopefully it's fixed.

**Pull request merged**
