### PR TITLE
Release 1.26.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* feat: Scan EIP-712 typed data signature requests (#3062)
* feat: include increaseAllowance in ApprovalEditor (#2984)
* feat: Show error on tx and safe creation if wallet balance is insufficient (#2986)

## Analytics
* Analytics: track Buy Crypto button (#3029)
* Analytics: track successfull QR scans (#3018)
* Analytics: key event types (#3088)

## Bug fixes & improvements
* fix: show "Unknown NFT" on transactions when token symbol value is null (#3065)
* fix: show fieldErrors in readonly input (#3060)
* Fix: [WalletConnect] rm app.optimism.io from blocked bridges (#3061)
* Fix: don't cut address in tx flow (#3041)
* Fix: [Safe Apps] align the share button (#3040)
* Fix: [WalletConnect] - user reject session reason (#3039)
* Fix: reconnect MetaMask only if unlocked (#3031)
* Fix: underline Help link
* Fix: use wallet balance from onboard (#3027)
* fix: Estimate gasLimit for safe creation (#3013)
* Fix: safe apps search performance (#3008)
* Fix: minor design tweaks (#3036)
* fix: allow localhost URLs with subdomains when adding custom safe apps (#3084)
* fix: Update Safe Apps header (#3085) by @manoranjith-shankar

## Refactoring
* Refactor: lazy-load BatchSidebar + remove animations in Safe Apps list (#3055)
* Refactor: remove Sentry performance tracing (#3052)
* Refactor: lazy-load tx flows (#3051)
* Refactor: [WalletConnect] lazy-load based on feature toggle (#3048)
* Refactor: [Recovery] lazy-load based on feature toggle (#3044)
* Refactor: reorganize Recovery feature files (#3042)
* Refactor: move theme from safe-react-components (#3038)

## Chores & e2e tests
* Chore: up safe-deployments version (#3069)
* Chore: optimize Lodash imports (#3054)
* Chore: update dependencies (#3032)
* Chore: update Next.js to 13.5.6 (#3030)
* Chore: create a release only if PR is merged (#3028)
* Tests: remove unused variables (#3063)
* Tests: fix history_2 test in regression (#3033)
* Tests: Add tests for spam token (#3023)
* Tests: Update tx builder and add tx history tests to smoke suite (#3020)
* Tests: Use latest stable Chrome version in tests (#3006)
* Tests: Fix test index (#3014)

### CODE REVIEW

**Comment by francovenica** [comment]
I'm seeing this error quite a bit. Best way to reproduce it is visit the homepage of an ethereum safe (probably the network is not a factor)

Visit:
https://release--walletweb.review-wallet-web.5afe.dev/home?safe=eth:0xb2d3e159342D8bA7a7bDffcB206Dd28BAfDAE997

image

**Comment by francovenica** [comment]
The rest of the tickets in the description are fine (those which the functionality can be tested, I skipped chores). 
The only ticket I wasn't able to check is the "Unknown NFT", since the token used as example now has a name, is not unknown anymore:
image

The rest of the regression still has to be done:
Connection with different wallets, Execution of different tx types, Safe adding&creation, Owners edditing, etc...

**Comment by liliya-soroka** [comment]
E2E tests passed - https://github.com/safe-global/safe-wallet-web/actions/runs/7444944482. I will continue regression

**Comment by liliya-soroka** [comment]
Can not execute tx using Ledger Nano X ( direct connection) . The same tx can be executed with Ledger on safe.global
image

**Comment by liliya-soroka** [comment]
Enable Social Login for regression in the RC

**Comment by liliya-soroka** [comment]
Stabilization board - https://www.notion.so/safe-global/01e0671b19524f5e82e3cf6d7aabea5b?v=6e17f110c34a43319977e361b28dfd96

**Comment by liliya-soroka** [comment]
https://github.com/safe-global/safe-wallet-web/actions/runs/7462729509 - e2e run passed

**Review by liliya-soroka — APPROVED** [review]

**Pull request merged**
