### PR TITLE
fix: chain names overflow menu on small resolutions

### LINKED ISSUE #2412: Chain names overflow menu
## Bug description

On small resolutions, the list of chain names overflow the menu area.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Reduce the height of the window and observe the chain names overflowing.

## Expected result

Chain names should remain within the menu area.

## Obtained result

Chain names overflow the menu area.

## Screenshots

image

### PR DESCRIPTION
**Pull request by chapati23**
## What it solves

Resolves #2412

(same as #2433 but this time with updated git config so I can actually sign the CLA 🙂 )

## How this PR fixes it

The `<Paper>` component surrounding the `<NetworkSelector>` had `overflow: visible`, which led to network names potentially being displayed outside the network selector box on small resolutions.

Overriding this specific style with `overflow: auto` fixes the issue and makes the network selector scrollable when vertical screen space is insufficient.

## How to test it

1. Open this branch on dev
2. Open the network selector on a normal desktop resolution and see that it still works as before
3. Open the network selector on a small resolution with low vertical pixel size so that the list of chain names is longer than the screen is able to show
4. See that there's now a scrollbar, and the chain names no longer overflow the surrounding menu box

## Screenshots

Screenshot 2023-08-23 at 17 03 00

## Checklist
* [x] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by chapati23** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chapati23** [comment]
recheck

**Comment by katspaugh** [comment]
Thanks @chapati23!

**Review by katspaugh — APPROVED** [review]

**Comment by francovenica** [comment]
LGTM.
Tested cloning his branch locally
network scroll

**Pull request merged**
