### PR TITLE
fix: Harden condition for loading spending limits

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Part of #2414 

## How this PR fixes it

- `getSpendingLimits` was called twice because the condition only checked for the existence of `tokenInfoFromBalances` but the initial value is an empty array so it should check the length of the array instead

## How to test it

1. Open a Safe with a spending limit
2. It should still be visible under settings and when trying to create a transaction

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by usame-algan** [comment]
I wonder what is the expected behaviour in case there are no tokens in a safe? Assuming `tokenInfoFromBalances` would always return an empty array we would not display the spending limits to the user anymore.

**Review by compojoom — APPROVED** [review]
I think that this should get our RPC count significantly down as due to this we were doing the queries twice.

**Comment by schmanu** [comment]
> Assuming `tokenInfoFromBalances` would always return an empty array we would not display the spending limits to the user anymore.

@usame-algan I think the `tokenInfoFromBalances` always contains an entry for the native token once fetched from the CGW - even if it is 0. I just setup Spending Limits on a Safe without any balances and they get displayed correctly in the settings.

**Comment by katspaugh** [comment]
@schmanu I think that's fine because the purpose of that check is to verify that the balances are fetched from CGW.
This could probably be more cleanly achieved via `const { balances, loading } = useBalances()`.

**Comment by francovenica** [comment]
Spending limit looks fine

Creation, edition, removal. 
With Native and ERC 20 token. 
Use of the spending limt with the user
Use all the tokens allowed
Check the refresh of the allowance

LGTM

**Pull request merged**
