### PR TITLE
Release 1.33.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* feat: speedup pending transactions (#3425)

## Analytics
* Analytics: reject tx events (#3516)

## Improvements and bug fixes
* fix: web3-onboard support for EIP6963 (#3518)
* Fix: [Tx Deletion] signTypedData fallback for Ledger (#3512)
* Fix: don't show onboard popup on reconnect for MetaMask, Rabby and Zerion (#3510)
* Fix: close Notifications popup after navigation (#3504)
* Fix: adjust bridge warning wording (#3506)
* Fix: extend bridge warnings list (#3505)
* Update eslint rules (#3475)
* Chore: adjust timezone in tests (#3507)

### CODE REVIEW

**Comment by liliya-soroka** [comment]
FF - MM wallet icon is not seen
image

**Comment by liliya-soroka** [comment]
regression run passed - https://github.com/safe-global/safe-wallet-web/actions/runs/8598661801

**Comment by liliya-soroka** [comment]
Board - https://www.notion.so/safe-global/87ec2a876ee84ad482be9a33ef537f57?v=7d8db5cf673b406abd47145938553073

**Comment by francovenica** [comment]
In the board there are only 3 tickets. beyond that I didn't have more issues.
Remember that delete tx doesn't work with trezor yet

Automation has passed and the regression went fine, so once the tickets have been clear we are good to release

**Comment by francovenica** [comment]
The fixes are good.

**Review by francovenica — APPROVED** [review]

**Pull request merged**
