### PR TITLE
Release 1.18.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* Feat: human-readable transaction descriptions (#2371)
* Feat: show Beamer NPS survey after a tx proposal (#2461)
* feat: allow setting fixed EIP1559 gas fees (#2398)
* Feat: show contract names in multisend summary (#2443)
* Feat: import/export in the Safe List sidebar (#2299)
* Feat: send deviceType to GTM (#2430)
* feat: add claim button to header (#2472)

## Bug fixes
* fix: close batch flow when removing last draft (#2453)
* Fix: multisend verification only worked for the latest contract version (#2439)
* Fix: WalletConnect v2 + MetaMask mobile (#2444)
* fix: chain names overflow menu on small resolutions (#2434)
* fix: TxFlow close button zindex (#2431)
* Fix: show known addresses in decoded tx data (#2423)
* Fix: hide Batch icon if not on a Safe route (#2426)
* Fix: do not sandbox safe icon URLs (#2421)
* Fix: sidebar links to queue if there are queued txs (#2357)
* fix: predicted Safe address on ZK chains (#2416)
* Fix: status widget for 1271 messages (#2415)
* fix: memoize deadline + smart contract check calls (#2411)
* Fix: wallet icons in dark mode (#2392)
* fix: do not fetch safe version on-chain (#2409)
* fix: Show readonly approval editor only for existing transactions (#2403)
* fix: Add addOwner route and open tx flow (#2399)
* Fix: text changes in Safe Creation (#2400)
* Fix: keep prev spending limits when polling (#2395)
* Fix: AddressInput identicon (#2393)

## Other improvements
* Refactor: update to Next 13 (#2436)
* Update @safe-global/safe-apps-sdk to ^8.0.0 (#2339)
* ~Use wallet RPC when possible (#2418)~ reverted
* Refactor: Safe creation hooks + rm unused files (#2417)
* Docs: update release-procedure.md (#2447)
* Tests: e2e batch transactions (#2406)
* Chore: fix dockerhub deployment (#2466)
* Rm WalletConnect v1 and Taho; reorder wallets (#2463)

### CODE REVIEW

**Comment by francovenica** [comment]
About beamer. here the popUp jumped when I signed+executed a tx. It is supposed to jump only when the tx is proposed. Can you check if the latest change of the ticket made it to this RC?

image

**Comment by francovenica** [comment]
I get errors like this when I connect with WC with OwnerA and I switch to OwnerB and I try to sign or execute a tx.
I can still see the owner changing in the top right corner, 
image
image

**Comment by francovenica** [comment]
I'm getting this error consistently:

They way I have to reproduce it is:
I have 2 safes loaded in the web app, so when I switch to the network in the top right it goes to the safe loaded in that network.
These are the safes:
eth:0x8675B754342754A30A2AeF474D114d8460bca19b
gno:0xB8d760a90a5ed54D3c2b3EFC231277e99188642A

By switching from the GNO safe to the ETH safe it crashes. Going from the ETH safe to the GNO doesn't causes any trouble. Reloading the page after the crash loads the ETH safe just fine.

This doesn't happen to me in prod with those 2 safes
Crash

**Comment by iamacook** [comment]
> EDIT: I know why this happened, The relayer. When you use the relayer the signing is off chain and technically we only propose the tx from our side. Is this something we should concern about?
> 
> ~About beamer. here the popUp jumped when I signed+executed a tx. It is supposed to jump only when the tx is proposed. Can you check if the latest change of the ticket made it to this RC?~

This [was discussed](https://5afe.slack.com/archives/C03DAGWJCR5/p1693466139954109?thread_ts=1693316521.309619&cid=C03DAGWJCR5) and deemed fine as is.

**Comment by katspaugh** [comment]
The found issues are fixed now, @liliya-soroka please check. 🙏

**Comment by liliya-soroka** [comment]
What was checked :
1. https://github.com/safe-global/safe-wallet-web/pull/2476 - no crash after switching from chain without airdrop to the chain with airdrop ( diff Safe token amounts)
2. connect to the safe on diff chains using MM browser extension , WC+mobile MM ( tx signing, execution, signing+execution)

**Comment by liliya-soroka** [comment]
1. Mobile pairing - no QR code ( might be regression issue , as QR code appears on prod in the same case)

https://github.com/safe-global/safe-wallet-web/assets/338622/c0b58cbc-49e2-41be-86a0-d6ed9c891dfd

**Comment by liliya-soroka** [comment]
2. "could not detect network" error appears for me on Gnosis Chain and Celo as in RC as on prod. Not a blocker for the RC from my point of view as it's not a regression.

**Review by schmanu — APPROVED** [review]
🏁

**Pull request merged**
