### PR TITLE
[Multichain] fix: Adjust multichain design [SW-244]

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves [SW-244](https://www.notion.so/safe-global/Small-design-tweaks-1118180fe57380e08ee4f1f3477f5c6b)

## How this PR fixes it

Addresses feedback from this document: https://www.notion.so/safe-global/Insights-Feedback-on-Multichain-10c8180fe57380eba5efded223e0aa70

- Reuses `NetworkLogosList` inside the SafeList
- Adjusts `NetworkLogosList` to optionally only display the first 4 networks

## How to test it

Compare screenshots to Figma design

## Screenshots
Screenshot 2024-09-30 at 15 05 46
Screenshot 2024-09-30 at 15 06 00
Screenshot 2024-09-30 at 15 07 10
Screenshot 2024-09-30 at 15 07 21

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Review by schmanu — COMMENTED** [review]
Its looking really nice.

Do you think we should revert this tooltip for the multichain Safes? Or is it still interesting for the case that there are 5+ chains?
Screenshot 2024-09-30 at 15 18 48

cc @TanyaEfremova

**Comment by usame-algan** [comment]
> Do you think we should revert this tooltip for the multichain Safes? Or is it still interesting for the case that there are 5+ chains?

I think we should at least show it if there are more than 5 safes otherwise it would just say +2 or something without the user knowing which other 2 networks there are.

**Review by schmanu — APPROVED** [review]
Vamos 🚀

**Comment by TanyaEfremova** [comment]
Agreed with @usame-algan regarding the tooltip. It still has additional value for >5 networks.

The only remark I have is the border color, it should be 'background-main' (so #ffffff). Could we do this small change? 
Otherwise, it looks great!

**Comment by usame-algan** [comment]
> The only remark I have is the border color, it should be 'background-main' (so #ffffff). Could we do this small change?

Thanks! Adjusted the border color to be `background.paper` so its not visible in the list against the background

**Pull request merged**
