### PR TITLE
fix: replacement nonce dropdown style

### LINKED ISSUE #2304: [Tx flow] Update transaction replacement dropdown style
## What is the feature about

The design of the nonce dropdown items for replacing a transaction needs to be aligned.

## The list of requirements

- Update the dropdown style

## Designs/sketches

image

Note: the width of the popper should be that of the longest transaction title.

## Links

- [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=1-5&mode=design&t=WbShkKUISF7wNfbP-0)

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #2304

## How this PR fixes it

The design of the replacement nonce dropdown has been aligned with [the designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=1-5&mode=design&t=WbShkKUISF7wNfbP-0).

## How to test it

Opent the transaction flow on a Safe and observe the recommended nonce in the dropdown list (as well as other queued transactions, if they exist).

## Screenshots

image

## Checklist
* [x] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by katspaugh** [comment]
Seems like the paddings are a bit too big.
Screenshot 2023-07-27 at 16 11 58

**Review by schmanu — COMMENTED** [review]
How about we also add the current Safe nonce to the drop-down? Has that been discussed? At least for the case where the recommended one differs from the current Safe nonce.

**Comment by katspaugh** [comment]
@schmanu in what situation do you think it could be helpful?

**Comment by katspaugh** [comment]
The top padding is still too big. It should be the same as the left-right padding:
Screenshot 2023-07-31 at 08 25 39

**Comment by iamacook** [comment]
> The top padding is still too big. It should be the same as the left-right padding: Screenshot 2023-07-31 at 08 25 39

Oversight working from the airport. I've reduced the y-axis padding.

**Review by katspaugh — APPROVED** [review]
Looks good!

**Comment by francovenica** [comment]
Looks neat.
image

**Pull request merged**
