### PR TITLE
fix: Close sidebar drawer when user navigates on mobile

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Closes the sidebar on mobile when navigating to a different page

## How to test it

1. Open a Safe on mobile or with a mobile viewport
2. Navigate to a different page
3. Observe the sidebar closes

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by usame-algan** [comment]
Ideally, we would call `onToggle` on button click but it requires us to prop drill the function 3 times which is not as clean as having a single `useEffect` imo.

**Review by katspaugh — APPROVED** [review]
👍

**Review by katspaugh — APPROVED** [review]
✅

**Comment by francovenica** [comment]
Nice, this solves this ticket #3482 . 

LGTM

**Pull request merged**
