### PR TITLE
Release 1.19.0

### PR DESCRIPTION
**Pull request by katspaugh**
##  🎁 Features
* Push notifications (#2369) <details>
Screenshot 2023-09-26 at 08 44 02</details>
* Human-readable transactions in history and queue (#2518) (A/B test) <details>
Screenshot 2023-09-26 at 08 48 49</details>
* Sign/execute pending transactions directly from the Dashboard (#2523) <details>Screenshot 2023-09-18 at 17 25 00</details>
* New connect button + deprecate mobile pairing (#2544) <details>Screenshot 2023-09-25 at 17 14 16</details>
* Allow safe apps to disable off-chain signing (#2441)

## 🐞 Bug fixes
* fix: use MultiSendCallOnly 1.3.0 for older Safes (#2528)
* fix: Update tx flow form when selecting a replacement nonce (#2520)
* fix: close transaction modal if already on `href` (#2527)
* fix: close transaction flow if Safe changes (#2526)
* fix: reset nonce if outdated (#2383)
* Fix: notification center width on mobile
* Fix: [Dashboard] better layout for pending txs (#2491)
* fix: use current/latest Safe deployments (#2467)
* style: welcome screen re-ordering enhancement for mobile view (#2474)
* Fix: reset body scroll after mobile pairing (#2489)
* Fix: update default value for Relay Service URL (#2488)
* Fix: Execute batch -> Bulk execute (#2464)
* fix: populate address from URL in load Safe flow (#2451)
* fix: don't track clicks on disabled elements (#2468)
* fix: adjust Ledger signatures for notifications (#2550)

## 🛠️ Miscellaneous
* Attach safe address to GTM (#2524)
* Chore: track tx errors on Sentry (#2483)
* Fix: update privacy policy (#2542)
* fix: boolean env vars (#2532)
* Cypress tests refactoring: PO model, safe app tests (#2522)
* Refactoring of existing Cypress tests (P2) (#2512)
* Refactor Cypress tests: address book and balance tests (#2502)

### CODE REVIEW

**Comment by francovenica** [comment]
Issue:

In the global preferences for notifications, unchecking and saving only one checkbox from one network unchecks the rest of the checkboxes
checkbox unchecking

**Comment by francovenica** [comment]
I'm leaving a note correcting something I said in the original Notifications EPIC:

The "Confirmation request" DOES work on safes 2/2. 
Debugging with Aaron today, I've found out that Firefox is very pesky with notifications. It seems that enabling/disabling notifications constantly can create issues (service workers and the indexDB)
I decied to use chrome as the browser for control, and it seems to be much more consistent with the messages.

Another note that I didn't say in the original EPIC but is worth mentioning:
"Confirmation request" is the only type of notification that looks at the owners who are receiving it. So if an owner signed the enabling of notifications and then is kicked out of the safe, he will no longer receive notificatons about "Confirmation request", but it WILL receive notifications about "tx executions" and "Tokens received". The user can still, as a non owner, unsubscribre from these notifications types.

**Comment by iamacook** [comment]
> I've found out that Firefox is very pesky with notifications. It seems that enabling/disabling notifications constantly can create issues (service workers and the indexDB) I decied to use chrome as the browser for control, and it seems to be much more consistent with the messages.

I can confirm that I get notifications in Firefox _and_ Chrome, even after unregistering the service worker/clearing the IndexedDB. It is concerning that it is so flakey for you but I hope that the user won't have to touch either of these.

> Another note that I didn't say in the original EPIC but is worth mentioning: "Confirmation request" is the only type of notification that looks at the owners who are receiving it. So if an owner signed the enabling of notifications and then is kicked out of the safe, he will no longer receive notificatons about "Confirmation request", but it WILL receive notifications about "tx executions" and "Tokens received". The user can still, as a non owner, unsubscribre from these notifications types.

We have mentioned this in the help article that will be linked to as per discussion with @kirkkonen and @TanyaEfremova.

**Comment by francovenica** [comment]
Issue:

In a brand new safe (or a safe that has never executed a transaction) the nonce field in the tx form shows the skeleton all the time and never shows the Nonce 0 as expected.
After executing that first transaction it works fine, so the issue is if the safe has to execute the nonce 0
image

**Comment by francovenica** [comment]
Messages are broken, the text overlaps all together. Maybe is because human-readable
image

This safe has messages: (turn on Prod CGW)
https://release_1_19_0--walletweb.review-wallet-web.5afe.dev/transactions/messages?safe=gor:0x0EDc6697427E9e9d62A1eE1A2951AfA7bE9e75B7

**Comment by usame-algan** [comment]
> In a brand new safe (or a safe that has never executed a transaction) the nonce field in the tx form shows the skeleton all the time and never shows the Nonce 0 as expected.
> Messages are broken, the text overlaps all together. Maybe is because human-readable

Nice finds! I've fixed both in #2562

**Comment by francovenica** [comment]
The 2 issues reported where fixed

Nonce 0 is shown just fine now
The messages look fine as well

image
image

**Comment by francovenica** [comment]
The rest of the ticket is fine.

I've checked the list in the description and that can be tested in the UI look good

I've done the regression:
Safe creation and adding
Tx creation / execution with Trezor, Ledger, MM extension, MM phone app via WC, Mobile pairing
Send funds, NFT's
Safe app (tx builder)
Execution un bulk
Message signing (using epi 1271 test app)
Owner edition (adding/removin/replacing)
Spending limit creation removal usage
Address book
Import/export
Settings in general
....

**Review by schmanu — APPROVED** [review]

**Comment by usame-algan** [comment]
recheck

**Pull request merged**
