### PR TITLE
Fix: [Tx Deletion] signTypedData fallback for Ledger

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

In Ethers v6, the signTypedData method unconditionally calls `eth_signTypedData_v4` that Ledger (and probably also Trezor) doesn't support. So I've added a fallback that calls `eth_signTypedData` if `eth_signTypedData_v4` fails.

## How to test it

Case 1:
* Propose a transaction with Ledger
* Delete that transaction with Ledger

Case 2:
* Sign a message with one of the signers being a Ledger

### CODE REVIEW

**Review by schmanu — APPROVED** [review]
👍 
Not sure if they are flaky but our AddressInput tests seem to fail. But there is no connection to the changes.

**Comment by francovenica** [comment]
Cancelling a tx with ledger works fine

Signing a message has Issues:

Signing messages is failing with ledger for me.
I tried with a LedgerX in Ethereum, singing the tx that Opensea asks to sign when connecting to it.
image

**Comment by francovenica** [comment]
Note:
We decided to test Trezor as well in this ticket. 
Trezor has issues for both, signing the Tx deletion and signing the Open sea message

Tx Deletion error:
image

For the openSea message, is the same error as the ledger

**Comment by francovenica** [comment]
Correction. It seems my ledger was locked at the time of signing the message. 
I was able to sign just fine with the ledgerX
image

**Comment by francovenica** [comment]
Signatures work again with both trezor one and ledgerX

**Comment by francovenica** [comment]
Given the issue of the Trezor is going to be fixed in another ticket we can merge this one

**Pull request merged**
