### PR TITLE
Release 1.42.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* feat: blockaid integration (#4029)
* Feat: add native staking teaser in sidebar (#4154)
* Feat: display a Network switch button when connected on the wrong chain (#4027)
* feat: Add support for proposing transactions as a delegate (#4017)
* feat: show Safe{Pass} points in header (#4064)
* Legal: update the terms page (#4178)

## Bug fixes
* Fix: hide SAP and Swaps if geoblocked (#4148)
* fix: avoid cleaning the async data when there is a reconsilation in the component (#4149)
* fix: Consider app category in the searchbar query filter (#4147)
* Highlight raw data transactions (#4146)
* fix: Watch nested safe transactions (#4057)
* Fix: (Swaps) sell token reactivity (#4145)
* fix: put execute button to be full width on mobile display (#4143)
* Fix: (css) center-align delegate warning (#4134)
* fix: inconsistent layout in dashboard pending transactions view  (#4034)

## Chores & tests
* Chore: update walletconnect packages (#4152)
* Chore(deps): Bump the npm_and_yarn group with 4 updates (#4153)
* Chore(deps): Bump classnames from 2.3.2 to 2.5.1 (#4137)
* Chore(deps): Bump react-dom and @types/react-dom (#4128)
* Tests: Fix failing regression tests (#4144)

### CODE REVIEW

**Comment by francovenica** [comment]
Note:
In this PR we are introducing back the ability of Delegates to propose transactions. Blockaid seems to have trouble to check these transactions as well. Even if is not a huge risk (since a delegate is somebody put there by the owners, so is supposed to be a trusted address) is another type of tx added to the list of tx's that Blockaid cannot check.
image

**Comment by francovenica** [comment]
@schmanu @katspaugh It seems blockaid is not working in the RC, in the sense that all txs show the "could not check" warning. This was what happened in the orginal PR and why we had to test it on localhost with a specific env key. Is there a way to make it work here?
image

**Comment by liliya-soroka** [comment]
Regression run was gree for the RC - https://github.com/safe-global/safe-wallet-web/actions/runs/10827096084

**Comment by liliya-soroka** [comment]
Issue: New label on dashboard at the right side of the screen 
image

**Comment by francovenica** [comment]
The Execute button is still broken for desktop resolutions under 1399px width
image

**Comment by francovenica** [comment]
The fix on the execute button in lower resolutions is not working properly, it also broke how the "Sign" button behaves in lower resolutions.
Currently in prod the break happens at 1199px, and in this fix the break happens at 1399 px, so is the "Sign" button and "execute" buttons both break in even higher resolutions.
A comparison how it currently works in Prod and in the RC:
Prod:
buttons in prod

RC:
buttons in RC

**Comment by clovisdasilvaneto** [comment]
Hey @francovenica just checked the button breakpoint issue, and looks like the breaking is happening at `1199px` as expected: https://www.awesomescreenshot.com/video/31566363?key=78176f8fb0c5c06ef7559a80a1da9c0d

**Comment by clovisdasilvaneto** [comment]
Same in the release address as well: https://www.awesomescreenshot.com/video/31566581?key=53e27be7823a0ea1cea53374eb2d1fcb

**Comment by clovisdasilvaneto** [comment]
@francovenica if you mean the button that is breaking is the *back button* I've sent a fix on this PR and will be merging it on this branch soon: https://github.com/safe-global/safe-wallet-web/pull/4181

**Comment by francovenica** [comment]
Yeah, my issue was the back button breaking in a new line between 1200 and 1399. I just checked and it looks good now. Thanks!

**Comment by liliya-soroka** [comment]
reject tx can not be scanned 
image

**Comment by liliya-soroka** [comment]
@schmanu 
1. dai transfer to the safe 
Balance change 0
Error for the safe 
image

**Comment by schmanu** [comment]
> @schmanu
> 
>     1. dai transfer to the safe
>        Balance change 0
>        Error for the safe
> 
> 
> image

The warning makes no sense but balance change 0 is correct as you send funds to yourself.

**Comment by francovenica** [comment]
The issue about the "Confirm" button being grayed out when in a different network is still present for the "Recovery tx"

Create a recovery for a user
Start a recovery with that user and execute it
The tx should be listed in the queue now
Switch networks while connected with the "Recoverer", the buttons are grayed out

image

**Comment by francovenica** [comment]
The tx you can execute to activate a safe cannot be checked by Blockaid. Should they even be checked? is true that you could send funds to an untrusted address, but given that the safe activation is done by the connected wallet and not the safe probably the tx should be exempt of being checked by Blockaid in the first place

image

**Pull request merged**
