### PR TITLE
Fix: soften fallback handler warning

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

The original custom fallback handler warning was added in #1781.

We got feedback from CowSwap that the current warning is too scary to the users when they enable a custom handler for TWAP orders. So we're changing the icon and message to be less alerting.

Official:
Screenshot 2023-11-01 at 13 43 06

Custom:
Screenshot 2023-11-01 at 13 43 28

Unset:
Screenshot 2023-11-01 at 13 48 14

### CODE REVIEW

**Review by schmanu — COMMENTED** [review]
If the CowSwap TWAP fallback handler is also static we could allowlist some individual addresses. If it is a completely unknown fallback handler I would prefer a warning.
What do you think?

**Comment by katspaugh** [comment]
@schmanu allowlist where?

**Comment by schmanu** [comment]
> @schmanu allowlist where?

For now we could have a list in our repo of known fallback handler addresses where we add the [CoW Extensible Fallback Handler addresses](https://github.com/cowprotocol/composable-cow/tree/ab3addad9bc05acdbf5fb040eb5c336209b58e31#deployed-contracts) 
But ideally that would live on the config service / gateway. 

I'm just thinking in general having an unexpected / inofficial fallbackhandler hints at a potentially risky setup. Or do we know many other dApps / protocols that use custom fallback handlers?

**Comment by katspaugh** [comment]
If you're implying hardcoding it, I wouldn't do it.

**Comment by liliya-soroka** [comment]
All custom fallbackhandlers will be green with the fix . I would check with the prod team if it's expected and safe
image

**Comment by katspaugh** [comment]
Fixed. ✅ 

Official:
Screenshot 2023-11-01 at 13 43 06

Custom:
Screenshot 2023-11-01 at 13 43 28

Unset:
Screenshot 2023-11-01 at 13 48 14

**Comment by liliya-soroka** [comment]
Verified

**Pull request merged**
