### PR TITLE
1.28.0

### PR DESCRIPTION
**Pull request by compojoom**
## Refactoring Power-Up! 💡

**Upgrade ethers to v6 and protocol-kit to v2 (#3087)**

We've upgraded our codebase to use ethers v6 and protocol-kit v2. For end users, nothing changes — everything continues to work as usual. For developers, this update greatly simplifies the implementation of upcoming functionalities. 🚀 

## Features
* feat: better number input (#3127)

## Bug fixes and improvements
* fix: a more accurate WC app detection (#3155)
* fix: TxType overlap/overflow (#3161)
* fix: Bug fixes and improvements for Dark Mode (#3102)
* fix: don't load Spindl if no SDK key (#3154)
* fix: left sidebar ui (#3152)
* fix: only rehydrate if social login is enabled (#3121)
* fix: ignore trusted flags on networks without token list (#3137)
* fix: show empty balance change response correctly (#3122)
* fix: send history timezone_offset to gateway (#3091)

## Test & Chores
* refactor: animated sidebar only on a Safe App page (#3131)
* tests: E2e - Remove owner - add signing action (#3076)
* refactor: Upgrade ethers to v6 and protocol-kit to v2 (#3087)
* chore: update WalletConnect SDK (#3158)

### CODE REVIEW

**Comment by katspaugh** [comment]
You should probably emphasize the ethers migration in the description as this is the biggest change. When we scan the list of releases a month later, this is what we’ll want to see in the change log in the first place, not the improved input :)

**Comment by francovenica** [comment]
Also when you create the ticket, use the actions in the top right to put it in the current project and column(In this case, I'd assume is ready for QA)

**Comment by liliya-soroka** [comment]
Board - https://www.notion.so/safe-global/ff0232fa363846ce9c666c4301ef6524?v=18f158137fca4d97bf4675ba16d02290

**Comment by schmanu** [comment]
Closing this to reopen from branch `release` for social login testing.

**Pull request closed without merging**
