### PR TITLE
Release 1.9.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* **Approval editor** – warn about token approvals and allow editing the amount (#1763)
* **Import and export** – save your entire Safe Wallet data as JSON and import in another browser (#1816)
* **Decoded transaction info** – show native transfers and multisend sub-transactions (#1899)
* **Relaying** – the option to execute transactions and Safe creations with the connected wallet (#1919 + #1924)
* **Cookie banner** – an improved design with more transparency about our cookies (#1849)

## Bug fixes
* fix: wrong message in safe creation relay (#1922)
* fix: improve relay error (#1921)
* Fix: isValidMasterCopy params
* fix: Multiple transactions when creating a safe (#1883)
* fix: Over-initialization of the safe core sdk (#1843)
* fix: fetch all balances if chain does not support default tokens (#1928)
* fix: don't scroll wrap in transaction list (#1915)
* Fix: useTxActions should accept origin (#1926)
* fix: Dashboard layout with relaying widget (#1911)
* fix: replaced safe_token with new icon (#1917)
* fix: Add fallback for empty data in ApprovalEditor (#1892)
* Update safe-deployments to latest version to support Neon contracts (#1877)
* fix: brand alignment inconsistencies (#1910)
* fix: remove slash from end of CLA links (#1907)
* fix: tweak wording of Safe Account/{Wallet} (#1901)
* fix: balance pagination test (#1895)
* fix: allow using the injected wallet on mobile (#1880)
* fix: refresh remaining relays after relay (#1885)
* fix: rename Safe Apps to Safe{Apps} (#1888)
* fix: Unhandled error for pending txs in queue (#1862)
* fix: check simulation call trace for reversion (#1861)
* fix: Unhandled exception in the Copy button #1782 (#1851)
* Fix: a better cookie banner layout (#1849)
* Fix: filter pending txs by safe address (#1836)
* fix: Dashboard widgets do not align correctly (#1867)
* Fix: redirect old tx id URLs (#1870)
* fix: create Safe App share URL in `useEffect` (#1866)
* fix: remove unnecessary dependency (#1841)
* fix: Unhandled exception in useOnboard (#1868)
* fix: Spending limits: Table header is displayed when no records #1703 (#1852)
* fix: Navigation tabs break the layout on mobile viewports (#1865)
* fix: Track most searched safe apps (#1827)
* fix(safe-apps): Add new Safe apps domain (#1765)
* Fix: track QR button in address inputs (#1935)

## Other improvements
* Chore: fix e2e tests (#1929)
* chore(deps-dev): bump @openzeppelin/contracts from 4.8.2 to 4.8.3 (#1873)
* app store button - replaced with next image (#1906)
* NFTs page: better select-all UI (#1904)
* Chore: repace http-server with serve (#1905)
* refactor: `SignOrExecute` elements (#1842)
* [e2e] Collapse expand all actions (#1801)
* refactor: remove `getWeb3` (#1837)

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]

**Comment by francovenica** [comment]
is the ticket #1921 merged properly? I don't see its effects in the RC
image

**Comment by iamacook** [comment]
> is the ticket #1921 merged properly? I don't see its effects in the RC image

Yes, #1921 was a small tweak on the frontend. Here's how it looked prior:

image

This still needs to be tackled on the backend.

**Comment by francovenica** [comment]
For the 1921 I was expecting for the error to say "unprocessable entity", will that be changed in the backend?

**Comment by iamacook** [comment]
> For the 1921 I was expecting for the error to say "unprocessable entity", will that be changed in the backend?

Yes, there is [an open issue](https://github.com/safe-global/safe-gelato-relay-service/issues/74) to improve the error responses.

**Comment by francovenica** [comment]
with the revert of the change logo, the old logo is back, but is too smal. A comparison between the RC and current prod build
image
image

**Comment by francovenica** [comment]
I'm seeing this error in the console by just standing in the /welcome page
https://release_1_9_0--webcore.review-web-core.5afe.dev/welcome

image

**Comment by francovenica** [comment]
I have an issue where a pending tx keeps disappearing from the queue tab and reappearing constantly.
The tx is a removal of a spending limit and is taking its time to be fully executed. Still I'd expect for the tx to not disappear while is being processed
Tomorrow I'll keep debugging to see if it happens with other types of tx 

test

**Comment by katspaugh** [comment]
@francovenica does it do that on prod too?

**Comment by katspaugh** [comment]
> I'm seeing this error in the console by just standing in the /welcome page
> EDIT: This happens after accepting all cookies in the "preferences" modal

@francovenica this is from Beamer. Let's ignore it for now, we're in contact with their support.

**Comment by francovenica** [comment]
@katspaugh no, I tried the same tx in prod and the tx doesn't go off and goes back like that. I'll keep trying to see if it happens all the time or not

**Comment by francovenica** [comment]
https://github.com/safe-global/safe-wallet-web/issues/1956 Here

**Comment by francovenica** [comment]
Besides that last issue I mentioned in the previous comment the RC is fine. Once that is fixed we can deploy

**Pull request merged**
