### PR TITLE
Analytics: update Privacy policy for Spindl + refactor legal pages

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

I've cleaned up the components folder a little bit and remove unnecessary directories.

Also updated the Privacy Policy to include information about Spindl and the tracking of signer addresses.

## How to test it

Just click through pages like Terms, Imprint, Cookie policy etc and check that nothing has changed visually.

### CODE REVIEW

**Comment by francovenica** [comment]
I don't consider this issues, but different behaviour from how it is now in prod. 
I don't mind deploying them as they are. Still for the record:

In "Privacy", these links work as anchors: they scroll you to the point you want to see. In this PR they refresh the page completely before scrolling you down
image

Some sub-bulletpoints have a larger font size than what it is in Prod. Here in privacy again:
image
image

**Comment by katspaugh** [comment]
Fixed the links, the font changes are intended.

**Comment by francovenica** [comment]
The links are still reloading the page. The URL that loads for the links it seems they are being tracked I guess? 
Let me know if it is intentional
image

**Comment by katspaugh** [comment]
It's not intentional, some weird stuff is going on with these links.

**Comment by katspaugh** [comment]
Fixed by making them JS links.

**Pull request merged**
