### PR TITLE
fixed whitespace in pending tx dashboard

### PR DESCRIPTION
**Pull request by ElizabethOgbee**
## What it solves

Resolves #

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by ElizabethOgbee** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by katspaugh — CHANGES_REQUESTED** [review]
Can you please cleanup the PR? There are a lot of changes unrelated to the CSS fix.

Also please fill out the PR description properly.

**Comment by ElizabethOgbee** [comment]
I am so sorry about that. I was having a 403 issue while trying to push to github which made me created so many commit unknowingly. In cleaning up the PR, should i clone and then create another branch? I'm a little bit confused as this is my first time contributing. I would realy appreciate your response

**Comment by katspaugh** [comment]
Probably the easiest would be to just do a `git reset --hard origin/main` and manually copy the necessary CSS changes (it's only a few).
Then commit and `git push -f` to the same branch.

**Comment by ElizabethOgbee** [comment]
Okay

**Comment by ElizabethOgbee** [comment]
I created another PR so you can cancel this PR

**Comment by usame-algan** [comment]
Closing this in favor of #2229

**Pull request closed without merging**
