### PR TITLE
Feat: redesign Safe List in sidebar

### PR DESCRIPTION
**Pull request by katspaugh**
Redesign the Safe List in the sidebar according to the new Login Page design (see #3233).

Displaying pending Txs and fiat balance will come in a separate PR

Screenshot 2024-02-13 at 11 37 49

### CODE REVIEW

**Comment by katspaugh** [comment]
Too many dividers :)

Screenshot 2024-02-16 at 12 56 14

**Comment by liliya-soroka** [comment]
To the comment above - looks different from the design - 
image

**Comment by liliya-soroka** [comment]
Verified and can be included into RC. Let's check it together with Counterfactual safe feature

**Comment by liliya-soroka** [comment]
@mike10ca , a new Side menu will brake our side bar menu regression cases - https://github.com/safe-global/safe-wallet-web/actions/runs/7960401233

**Pull request merged**
