### PR TITLE
Release 1.48.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* Epic: sidebar improvements (#4442)
* feat: allow signing with owned parent Safes (#4406)
* Feat: featured Safe Apps on dashboard (#4644)

## Refactoring
* Refactor: upgrade to Next 15 (#4485)
* Refactor: rm unnecessary tx decoding (#4541)
* Refactor: sidebar hooks and components
* Refactor: restore old MUI props (#4620)

## Bug fixes
* fix: Cap max expiry for setTimeout in useIsExpiredSwap (#4674)
* fix: add event labels to opening and (un-)pinning of Safe Apps (#4582)
* Fix: replace "signer(s)" with "N signers" or "1 signer" (#4550)
* fix: update `wallet_getCallsStatus` spec. (#4569)
* fix: Don't break array elements in tx details into multiple lines if empty (#4571)
* fix: Advanced safe creation address computation (#4564)
* fix: Init Safe SDK for replayed safes (#4567)
* fix: remove unnecessary log (#4570)
* fix: only return "next" transactions as pending (#4568)
* fix: Disable transaction buttons until sdk is initialized (#4405)
* fix: fetch safe overviews including untrusted token fiatTotal (#4495)
* Fix: WC unit tests (#4553)
* Fix: remove old app store button (#4546)
* Fix: section heading in terms (#4545)
* Fix: mui accordion background (#4543)

## Chores
* Chore: extract terms version into a separate file for a smaller build (#4584)
* Chore: fix lodash imports (#4580)
* Chore(deps): Bump ethers from 6.11.1 to 6.13.4 (#4557)
* Chore: replace @walletconnect packages with @reown/walletkit (#4548)
* Chore: update walletconnect packages
* Chore: update cgw sdk to stable version
* Docs: update .env.example

## Tests
* Tests: Fix tests (#4586)
* Tests: Add using of mock safe address (#4581)
* Tests: Add timeout for drain account app (#4579)
* Tests: Add sidebar tests (#4577)
* Tests: Add regex to handle my accounts (#4574)
* Tests: Add safe pin tests (#4573)
* Tests: Fix sidebar and staking tests (#4566)
* Update import export tests (#4551)
* Tests: Add staking history tests (#4549)
* Tests: Add safe apps tests (#4544)
* Tests: Add proposers tests (#4542)
* Tests: Add proposer tests (#4536)

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]

**Comment by liliya-soroka** [comment]
- [ ]  Wrong network in the Edit entry pop up _
Steps: 
1. Open the side menu and try to add name for the safe on Sepolia when connected EOA is on Ethereum
Expected result:  Safe network should be displayed instead of connected EOA network
image

**Comment by liliya-soroka** [comment]
- [ ] Just activated safe has "read-only" mark in the side menu when the owner is connected
Steps:
1. create a CF with connected EOA as an owner with Pay later option ( one network)
2. activate the safe from the dashboard with the same EOA ( owner)
3. Open side bar after activation
Current result: The safe has Read-only mark when the owner is connected . The manual page refresh is required to update the sate 
image

**Comment by francovenica** [comment]
minor issue

There is a ticket where we changed signer/signers depending on if there was more than 1 signer.
There is the situation where if a user is removed from a safe with 2 owners, the ending result should say "1 out of 1 signer" but it still says signers:
- Have a safe with 2 owners
- Remove one
- In the review step see the wording

image

**Comment by liliya-soroka** [comment]
we are working on the https://www.notion.so/safe-global/Ledger-Off-chain-messages-signing-with-Ledger-wrong-messages-and-2-requests-15f8180fe57380aba736d75c03533055?pvs=4 to include the Ledger update in the release

**Pull request merged**
