### PR TITLE
Release 1.46.0

### PR DESCRIPTION
**Pull request by usame-algan**
## Features
* feat: Safe Proposers (#4426)
* Feat: indexing status (#4258)

## Refactors
* Refactor: unify confirmations in the transaction flow (#4177)

## Tests
* Tests: Fix add owner test (#4480)
* Tests: Multichain sidebar tests (#4476)
* Tests: Fix regression tests (#4470)
* Tests: Add twap tests (#4455)

### CODE REVIEW

**Comment by francovenica** [comment]
In the Prod CGW the Proposer sections shows up, but the "Add proposer" button does not.
With the Stg CGW it does show and everything works fine.

image

**Comment by francovenica** [comment]
There is an issue where the proposers cannot delete himself for not being the owner of the safe:
image

**Comment by francovenica** [comment]
This whole status block shouldn't show for a proposer, since the tx is not getting any new signature.
I'd hide it if the person creating the tx is a proposer and is creating a standard tx (I say it like this because it still should show up for when he uses spending limit for example)
image

**Comment by francovenica** [comment]
The issues reported were fixed:

The add proposer shows now for prod cgw
The proposer can delete himself
The status block doesn't show the +1 anymore during tx creation

**Review by jmealy — APPROVED** [review]

**Pull request merged**
