### PR TITLE
Release 1.35.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* feat: disable blind signing by default (#3605)
* feat: [Counterfactual] Show pending status on dashboard (#3495)

## Bug fixes
* fix: show input error if chosen nonce is not an integer (#3609)
* Fix: governance -> community (#3602)
* Fix: link to the accounts page from the logo (#3577)
* fix: open info page in new tab (#3582)
* Fix: update the Safe Apps SDK link (#3537)
* Fix: use wallet_addEthereumChain if cannot switch chain (#3563)
* fix: Dashboard widget color in dark mode (#3565)
* Fix: allow deleting only last tx and duplicates (#3554)
* fix: Hide "add to address book" when address already in the address book (#3558)
* Fix: make Connect wallet primary CTA on the Accounts page (#3538)
* Fix: Change disabled tx button tooltip text (#3500)
* fix: Show Safe activation status in safe list (#3493)

## Chores & tests
* Refactor: migrate the relay API (#3514)
* tests: adjust env variables in tests (#3542)
* Tests: add protocol kit integration in cypress project (#3540)
* tests: handle deletion of multiple recoverers (#3545)
* Chore: update the PR review domain (#3620)
* Tests: add wait time (#3580)
* Tests: update send funds tests (#3578)
* Tests: update workflow to add wallet credentials (#3575)
* tests: add core sdk integration to cypress tests (#3566)
* chore: add a build of storybook to PRs (#3556)
* chore: remove unused safe-core-sdk dependencies (#3547)

### CODE REVIEW

**Comment by francovenica** [comment]
I'm not able to use the example app to re-test 3605 ticket. I cannot use it even in the original PR, so I'll reach Manu as soon as I'm available so we can check that part
image

**Comment by francovenica** [comment]
Run the regression, worked fine

Created a board for issues in case we find any: https://www.notion.so/safe-global/a9aab340d6544cecb2c9be2c654a2c62?v=fe4919f55fb34c82afc07f08552c7967&p=040cfae61fb940c2a96c43d4a98f665d&pm=s

**Comment by katspaugh** [comment]
@francovenica WalletConnect should work now.

**Comment by francovenica** [comment]
The last fixes work fine.

The RC looks good to me

**Review by francovenica — APPROVED** [review]

**Pull request merged**
