### PR TITLE
Analytcs: execution via role event

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Role-based executions were previously tracked as separate events preceding a `tx_executed` event but it's more inline with our existing events to track them as `tx_executed` with a custom `eventAction`.

Edit: extended the same to spending limit transactions.

### 1
* Make a token transfer using Spending Limits
* In the console, the `tx_created` and `tx_executed` events should have a `Created/Executed via spending limit` action

### 2
* Create a Roles-based tx and execute it
* In the console, the `tx_created` and `tx_executed` events should have a `Created/Executed via role` action

### CODE REVIEW

**Review by schmanu — APPROVED** [review]
Makes sense. I think we should also refactor and add `EXECUTE_VIA_SPENDING_LIMIT` to be consistent.

**Comment by alicecha** [comment]
Could we add the same eventAction to the other transaction Custom Events: tx-created (and tx_confirmed + tx_signed if applicable)?

**Review by jfschwarz — APPROVED** [review]

**Review by alicecha — APPROVED** [review]
Looks good.

**Comment by liliya-soroka** [comment]
image
image

**Pull request merged**
