### PR TITLE
Release 1.22.0

### PR DESCRIPTION
**Pull request by schmanu**
# Features
- Seedless-onboarding (#2534)

# Bug Fixes
- redirect /wc URL (#2747)

# Chores
- Optimize docker image (#2771) 

# Tests
- Add safe apps tests (#2751) 
- Update workflow to enable tests run in parallel (#2739) 
- Make tests independent

### CODE REVIEW

**Comment by schmanu** [comment]
We cannot merge this yet.
We want to include the following PRs to this release which are currently in QA:
#2782
#2778

**Comment by francovenica** [comment]
Issue:

If you are connected with WC (using a MM phone app) and then, with the social login you change your password, after the page refreshes, the WC new feature shows that the safe is connected to itself

- Login with WC using the MM phone app
- Connect with social login
- Change your password
- See how the page refreshes itself
- Check the WC feature in the topbar
- Change wallet from social login back to WC and check the address

RC1

**Comment by usame-algan** [comment]
> If you are connected with WC (using a MM phone app) and then, with the social login you change your password, after the page refreshes, the WC new feature shows that the safe is connected to itself

This is strange, I can't reproduce it. Can you show an example of the whole flow starting from when you connect WC to MM app?

**Comment by liliya-soroka** [comment]
The error in case of paying from the social login address when not enough balance. The error text is unexpected and says nothing to the user
image

**Comment by usame-algan** [comment]
> > If you are connected with WC (using a MM phone app) and then, with the social login you change your password, after the page refreshes, the WC new feature shows that the safe is connected to itself
> 
> This is strange, I can't reproduce it. Can you show an example of the whole flow starting from when you connect WC to MM app?

After doing it together I can also reproduce this issue on prod. The steps are as following:

1. Open a Safe where your MM mobile app is an owner
2. Connect via WC to that safe
3. Observe the correct address in the header
4. Reload the page
5. Observe WC shows the safe address

Since this also happens on prod I suggest to create a separate issue

**Comment by francovenica** [comment]
So the issue with WC had nothing to do with seedless or the password, it was just the refreshing of the page. Also the issue is already in prod.
Still I'd like to see if we can fix it now so it can go live soon
Here's a ticket for it

https://github.com/safe-global/safe-wallet-web/issues/2790
cc @usame-algan

**Comment by francovenica** [comment]
I've checked the mergin of the tickets regarding assets widget in the dashboard and banner in the assets tab. Also checked the fix on the dashboard assets widget for mobile viewport. 
Those look good

**Comment by francovenica** [comment]
The RC looks good.

Notes:

I think is agreed that the issue of WC will be tackled in a different ticket and released later. I'm ok with that. Hopefully we can release it as a stand alone "hot fix" during the week.
We got the RC about the warning of running out of relayer usage. If that one is merged we should take a quick look after
It was mentioned that the "Buy token" button in the dashboard widget for mobile has a small style issue. Usame said he has to fix that one

**Comment by katspaugh** [comment]
@usame-algan will adjust the staging config.

**Comment by liliya-soroka** [comment]
I have an issue in the case of switching between the Goerli and Gnosis chains when social login is used.

https://github.com/safe-global/safe-wallet-web/assets/338622/b67d3c40-c96c-444e-9a6c-fb1442e6b97a

**Comment by liliya-soroka** [comment]
QR code should be changed if the prefix is off
image

**Pull request merged**
