### PR TITLE
Release 1.16.0

### PR DESCRIPTION
**Pull request by katspaugh**
### Features
* Feat: emoji identicons (#2305)
* Feat: show delegates (#2324)
* Feat: batch any tx (#2254)
* feat: Safe App info button (#1726)

### Bug fixes
* fix: Use PNG instead of SVG for Redefine logo (#2362)
* fix: Replace transaction with 0 nonce (#2361)
* Fix: prevent an early redirect on the Safe Apps share page (#2358)
* Fix: cookie prefs checked checkbox color (#2356)
* Fix: tx can have been created w/o signatures (#2354)
* fix: limit `origin` length (#2334)
* Fix: prevent key prop warning in EthHashInfo (#2351)
* fix: Open custom safe apps on click (#2350)
* Fix: warn if tx was already signed by connected wallet (#2322)
* fix: Reopen QR modal in safe creation (#2294)
* fix: execute icon colour in dark mode (#2338)
* fix: don't close flow in Safe Apps (#2333)
* fix: replacement nonce dropdown style (#2318)
* Fix: mobile pairing check (#2327)
* Fix: always keep the nonce of existing txs (#2323)
* Fix: minimize queue drawer when tx modal is opened (#2317)
* Fix: make tx modal higher than queue drawer (#2312)
* fix: centralise flow + reduce success screen width (#2309)
* fix: show failed simulations correctly (#2308)
* fix: show error for reverted txs (#2302)
* fix: use the deployment by `chainId` (#2246)
* fix: also format `inputProps['onChange']` (#2293)
* fix: Show Tenderly fail if there is a call trace error (#2290)
* fix: trim/remove leading zeros from values (#2284)
* fix: update privacy policy for mobile onboarding (#2282)
* fix: highlight confirmed status when signer confirms (#2279)
* fix: Update message signing link in settings (#2273)
* fix: resolve third party dependency (#2255)
* fix: Safe creation/batch execution gas estimation (#2232)
* fix: update token price tooltip (#2257)
* fix: autoconnect to WC v2 on mobile (#2238)
* fix: only initiate WC v2 module if project id provided (#2228)

### Improvements
* feat: add "Transaction is executed" to stepper (#2328)
* [EPIC] SEP #5 - Update header/widget (#2213)
* fix: `useAsync` dependency arrays (#2291)
* Refactor: fetch pending queue only in 1/N Safes (#2353)
* Refactor: onboard auto connect (#2343)
* chore: fix network name selection in E2E (#2267)

### CODE REVIEW

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
In mobile, I see this in the topbar.
The bell for notifications wasn't there before and now is pushing the network out of bounds. 
image

**Comment by francovenica** [comment]
Im sure we fixed this issue in its PR. WC v1 doesn't show the name of the wallet you are connecting with
image

**Comment by francovenica** [comment]
Beyond that small issue for mobile the rest RC looks good.
I've checked the tickets on the description, except some that are covered by a regression and some tickets about delegates that can only be done with "MM inst"

The regression looks good. Testedly mostly in GNO, ETH and Goerli
Safe creation / adding, 
Tx creation/execution/rejection/replacement
Spending limit
Address book
Apps (tested just a few)
Assets list
Import/export of data
Adv parameters
Relayer
Simulations (tenderly and redefine)
Connecting with different wallets (mobile pairing, MM WCv1, Rainbow WCv2, trezor, ledger, MM extension)
...

**Comment by katspaugh** [comment]
> In mobile, I see this in the topbar. (Can be seen using the emulation with chrome)

Fixed [here](https://github.com/safe-global/safe-wallet-web/pull/2376/commits/3f5dc309c93406e860baf79604a4fe12168561f7). Thanks Franco!

**Comment by francovenica** [comment]
There is still the issue present when no wallet is connected. I'll create a ticket to solve it in the next iteration
image

**Pull request merged**
