### PR TITLE
Release 1.14.0

### PR DESCRIPTION
**Pull request by katspaugh**
## 🐞 Bug fixes
* fix: revert Ledger module (#2215) – restoring previous Ledger connection UI
* fix: Allow non-owners with spending limit to execute transaction (#2121) by @elgatovital 
* Fix: checked box color in CookieBanner (#2199)
* fix: remove "Where's my wallet?" info (#2171)
* fix: don't check WC v1 session for v2 reconnection (#2178)
* Fix: /apps/open redirect (#2177)
* Fix: keystone modal scroll (#2170)
* Fix: reset tx list pages when Safe is changed (#2168)
* fix: remove creation modal query param on close (#2167)

## 🎁 Improvements
* chore: update deployment-related packages (#2217)
* fix: upgrade `@web3-onboard/core` (#2195)
* Tests: change token counter (#2179)
* Docs: fix readme formatting (#2159)

### CODE REVIEW

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
https://github.com/safe-global/safe-wallet-web/issues/2221
I cannot connect with ledger directly in prod so I cannot see if this issue is already happening there.

**Comment by francovenica** [comment]
I'm seeing this error in polygon when I reach the review step of safe creation. It happens with any wallet. 
The error is different in this RC and prod. I don't know if it worth having its own ticket:

RC:
image

Prod:
image

**Comment by schmanu** [comment]
@francovenica 
I cannot reproduce that error in the RC. Can you still reproduce it? Otherwise it could have been a temporary RPC problem.

**Comment by liliya-soroka** [comment]
@JagoFigueroa  to check Safe Apps before the release

**Comment by liliya-soroka** [comment]
@francovenica , keystone checked - works as expected

**Comment by francovenica** [comment]
The comment I made about polygon showing an error in the console when reaching the review step doesn't happen anymore, so it seems it was a temporary issue

**Comment by francovenica** [comment]
The rest of the RC is fine (tickets listed and regression)

I still have the issue of creating safes in Polygon ( I was able to do it on ETH once).

**Comment by schmanu** [comment]
I found a bug in our Execute transaction modal (for a fully signed tx):

The "Execute Transaction"-checkbox is disabled (as expected) but not checked.
Screenshot 2023-07-05 at 09 25 28

This happens on the RC but not in prod.

**Comment by usame-algan** [comment]
> The "Execute Transaction"-checkbox is disabled (as expected) but not checked.

Should be fixed now.

**Comment by katspaugh** [comment]
The Ledger+Polygon issue will be solved separately since it touches on more than just Ledger.

**Pull request merged**
