### PR TITLE
style: welcome screen re-ordering enhancement for mobile view

### LINKED ISSUE #2473: Minor enhancement for mobile view: Welcome screen ordering
## What is the feature about

Screenshot 2023-08-30 at 18 07 06

rearranging the order of welcome to safe and data import.

### PR DESCRIPTION
**Pull request by udhaykumarbala**
## What it solves
It changes the order of "welcome to safe{wallet}" component in the welcome screen in mobile view

Resolves #2473 

## How this PR fixes it
Using the Row-reverse property of grid, it changes the order of the components on mobile view

## How to test it
In desktop view, The import component will be in left and the welcome component will be in right
In mobile view, The welcome component will be in top and the import component will be in bottom

## Screenshots
Desktop:
CleanShot 2023-08-31 at 09 07 46@2x
Mobile:
CleanShot 2023-08-31 at 09 08 36@2x

## Checklist
* [x] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by udhaykumarbala** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by udhaykumarbala** [comment]
recheck

**Comment by udhaykumarbala** [comment]
recheck

**Review by katspaugh — APPROVED** [review]
Excellent, thank you!

**Comment by udhaykumarbala** [comment]
Hi @katspaugh, Do i need to fix the test cases ?

**Comment by katspaugh** [comment]
No, it's fine, they fail because of permissions.

**Comment by udhaykumarbala** [comment]
> No, it's fine, they fail because of permissions.

cool

**Comment by francovenica** [comment]
I think is not correct. 
If I unserstood correctly, it was just the Data import block the one that should be in the bottom, but the "My safe accounts" should still be on the top.
@johannesmoormann can you clarifiy just in case?

image

**Comment by francovenica** [comment]
@udhaykumarbala I talked with @johannesmoormann and yes, only the Import/Export block should be below, the "My safe Accounts" should still be on the top in mobile.

**Comment by francovenica** [comment]
@usame-algan maybe can you replicate what the contributor did in his branch plus the fix I asked? 
I'd close this ticket but keep the original issue open

cc @katspaugh

**Comment by udhaykumarbala** [comment]
updated screenshots

Mobile:
CleanShot 2023-09-05 at 12 50 02@2x

Desktop:
CleanShot 2023-09-05 at 12 51 49@2x

Hi @francovenica , i updated the PR please check the screenshots

**Comment by francovenica** [comment]
Looks good now. Thanks!

**Pull request merged**
