### PR TITLE
Release 1.10.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
- [EIP-1271 Sync] Synchronous signing flow for arbitrary thresholds (#1630)

## UX improvements
- Make it easier to paste eth addresses (#1897)
- Add "Advanced details" title in tx details (#1966)
- Split import/export data settings panes
- Improve array decoding (#1965)
- Improve "wrong chain" switching UX (#1937)
- Support injected wallet icons (#1953)

## Bug fixes
- Don't refresh main component on first page load (#1985)
- Improve disable condition and tooltip tile on `TxSummary` buttons (#1969)
- Fix env-dependent legal pages (#1982)
- Redirect non-existing "Messages" tab (#1973)
- Fix acronyms in camelCaseToSpaces (#1964)
- Update copyright text in footer (#1945)
- Fix sandbox safe app icons in tx list (#1942)

## Refactoring and chores
- Pass dockerhub project id from github secrets (#1977)
- Refactor executeTx hook (#1949)
- "Accept selection" in e2e tests (#1950)
- Rename the repo to safe-wallet-web (#1934)
- refactor: upgrade + optimise Redux (#1981)

### CODE REVIEW

**Comment by liliya-soroka** [comment]
1. Cowswap on Goerli - Swap ETH to Dai with Wrap in the middle 
image

**Comment by liliya-soroka** [comment]
2. Sign message with T&C  from Opensea doesn't appear on the safe side on Goerli and Polygon for all my safes and for one @schmanu 's safe.  T&C was cancelled once

**Comment by francovenica** [comment]
issue: 
After importing data through the buttons on the sidebar the safe don't show up listed there. This work fine in current prod build
image

Send me a message and I can share a file with data

**Comment by francovenica** [comment]
Beyond this issue the rest is working fine. 
Manu already responded to Lili's concerns and for me it worked as well as the EIP1271 epic.
The rest of the tickets are fine and the regression went well.

After that issue is fixed let me know. I'll check quickly and we can release it

**Comment by katspaugh** [comment]
@francovenica it's fixed now 👍

**Pull request merged**
